### PR TITLE
Change session timeout to 24 hrs

### PR DESCRIPTION
**Pull request by hlilje**
Changes the session timeout from default to 24 hrs.
Should the ticket expiration also be changed?

### CODE REVIEW

**Comment by dflemstr** [comment]
Can somebody test this manually before we merge?

**Comment by hlilje** [comment]
I haven't had time to test this, but I forgot how we could get CAS to authorise the application when running on localhost.
I think you just needed to change the request url, but now the KTH login service seems to reject the locally running app for being a "non-authorised web service".
Even then, what would be a good way to test this without waiting for 24 hrs? I was thinking something like changing it to a minute or something and see if that makes the session expire.

**Comment by hlilje** [comment]
Maybe it's worth merging this even though no one has time to properly test it, if the current timeout is an issue? @dflemstr

**Comment by dflemstr** [comment]
Just merge :)

**Pull request merged**
